### ISSUE TITLE
Jalankan command untuk optimization (cache, dsb).

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#162]
https://github.com/jabardigitalservice/reservasi-backend/blob/d56a44f8eddeb7922fc545be8f331b0c5df5f974/docker/docker-entrypoint.sh#L5-L8

**Referensi:**
https://laravel.com/docs/8.x/deployment#optimization

**Comment by iprasetyaa** [comment]
Mas @yohang88, kalau di exising, untuk command yang ada di referensi tersebut sudah ada disini :
https://github.com/jabardigitalservice/reservasi-backend/blob/d56a44f8eddeb7922fc545be8f331b0c5df5f974/Dockerfile#L76

Apakah perintah tersebut harus dipindahkan ke entrypoint atau cukup di Dockerfile saja Mas?

**Comment by yohang88** [comment]
@iprasetyaa sip mantap, tinggal ditambahkan aja config caching, route caching, dsb itu 😁

**Comment by samudra-ajri** [comment]
Sepertinya memang hanya menambahkan `config:cache` dan `route:cache` saja ya, Mas @yohang88 ?

https://github.com/jabardigitalservice/reservasi-backend/compare/feature-add-optimization

**Comment by yohang88** [comment]
@samudra-ajri ghaasss 💯

**Comment by iprasetyaa** [comment]
@jabardigitalservice/jds-backend bisi ada yg belum, gas gas

**Comment by samudra-ajri** [comment]
Need to be reviewed #164

**Comment by yohang88** [comment]
Siiipp makasih banyak @samudra-ajri @iprasetyaa 🚀
