### ISSUE TITLE
Sebaiknya menggunakan label di Enum dan Language Dictionary

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#47]
https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Mail/ReservationApprovalMail.php#L29-L32

Saya lihat tulisan "Ditulis" dan "Ditolak" ini masih hardcode, rawan duplikasi di banyak file 😁 

Di package enum ada fitur labels https://github.com/spatie/enum#enum-labels, ini bisa dipakai ga ya?

Kalau bisa, maka sebaiknya pakai label ini dan dikombinasikan dengan file language/dictionary di Laravel.

**Comment by rizkyrmsyah** [comment]
kalau yg ini mau saya hilangin mas, karena flow yg sekarang gak ada approval

**Comment by yohang88** [comment]
@rizkyrmsyah ya tapi fokusnya bukan itu sih 😁 Terlepas dari flownya berubah atau enggak, pertanyaan saya hal-hal di atas bisa dilakukan enggak? 😁

**Comment by setiadijoe** [comment]
Untuk selanjutnya itu bisa kang dilakukan jadi nanti pake enum kayak contoh kasus terkait `resource_type` itu udah pake enum. Untuk saat ini yang dibagian reservation approval tidak digunakan kang @yohang88 . cc @rizkyrmsyah

**Comment by setiadijoe** [comment]
Reference with issue #42
