### ISSUE TITLE
Seharusnya menggunakan Event & Listener, bukan Model Observer

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#48]
https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Observers/ReservationObserver.php#L20-L23

https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Observers/ReservationObserver.php#L31-L45

Jika menggunakan Model Observer (on-create dan on-update), artinya ini akan berlaku global, logic apapun yang melakukan create atau update model, akan mengeksekusi observer ini. 

Padahal, bisa jadi ada use case lain, misal ada fungsi lain yang perlu membuat atau mengupdate Model Reservation ini, namun tidak diharapkan mengeksekusi fitur kirim Email, dsb. Contoh: misal ada kebutuhan integrasi, bulk import, dsb. 

Maka yang lebih tepat untuk kebutuhan ini adalah Event dan Listener. Dan Event-Listener ini dilakukan di Controller / di logic yang memang hanya dibutuhkan saja, tidak perlu global di Model.

**Referensi:**
https://laravel.com/docs/8.x/events

**Comment by setiadijoe** [comment]
issue yang ini terkait dengan issue yang #42 yang tadi udah dimerge ya mas @yohang88
