### ISSUE TITLE
Seharusnya backend mengirimkan format Timestamp/Datetime sesuai standar ISO

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#49]
https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Models/Reservation.php#L45-L48

Laravel sesuai standar sudah mengikuti standar ISO ini, sehingga tidak perlu di-cast menjadi format lain 😁 .

**Referensi:**
https://wiki.digitalservice.id/doc/api-specdesign-ZjmiAeN3Qm

**Comment by setiadijoe** [comment]
itu diperlukan karena responsenya seperti ini kang @yohang88 kalau gak diformat
            `"start_time": "2021-03-01T07:17:00.000000Z",
            "end_time": "2021-03-01T07:18:00.000000Z",`
jadi mau diformat langsung

CMIIW mang @ayocodingit
