### ISSUE TITLE
Untuk apa getCheckTimeEditValidAttribute() ?

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#50]
https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Models/Reservation.php#L105-L108

Ini untuk apa ya? 😁

**Comment by setiadijoe** [comment]
cc kang @ayocodingit , untuk function itu buat apa ya? soalnya aku cek di codingannya gak ada yang pake nih. Apa boleh klo dihapus kang?

**Comment by ayocodingit** [comment]
Ini untuk vek validasi saat edit maksimal sebelum 30 menit

**Comment by setiadijoe** [comment]
yang ini kan maksudnya pengecekan body request ya? pengecekannya bukannya udah ada di body request, jadi kenapa perlu ditambah lagi? @ayocodingit

**Comment by ayocodingit** [comment]
Jadi validasi edit maksimal 30 menit nya di hapus yah . Bukanya tetep itu mah harus ada kan validasi buat edit

**Comment by setiadijoe** [comment]
berarti yang ini aku biarin aja dulu klo gitu kang. Sip infonya kang

**Comment by ayocodingit** [comment]
tapi kenapa aku liat validasi edit maksimal 30 menit yang abort if ko ilang yah @setiadijoe 
sebenernya itu salah penempatannya aja tapi secara fitur sudah jalan

**Comment by setiadijoe** [comment]
itu kemarin aku kira itu sama pengecekannya, nanti aku coba balikin lagi dan coba balikin lagi kang @ayocodingit , sebetulnya masih agak bingung itu yang update yang pengecekannya bagusnya dimananya
nanti aku ballikin lagi

**Comment by ayocodingit** [comment]
Okey sepp

**Comment by yohang88** [comment]
Maap maap saya masih kurang paham apa goal-nya 😂

**Comment by ayocodingit** [comment]
> Maap maap saya masih kurang paham apa goal-nya joy

goalnya itu mendapatkan validasi edit maksimal 30 menit aku buat di model biar pemanggilannya jadi singkat 
`Carbon::now('+07:00') > $this->start_time->subMinutes(30); `

**Comment by rindibudiaramdhan** [comment]
> > Maap maap saya masih kurang paham apa goal-nya joy
> 
> goalnya itu mendapatkan validasi edit maksimal 30 menit aku buat di model biar pemanggilannya jadi singkat
> `Carbon::now('+07:00') > $this->start_time->subMinutes(30); `


thread PR nya disini ya kang @ayocodingit ? https://github.com/jabardigitalservice/reservasi-backend/pull/26

**Comment by yohang88** [comment]
I see, baru baca PR #26, berarti memang ada requirement baru ya itu (edit reservasi hanya bisa dilakukan 30 menit sebelum reservasi dimulai), saya cek di Trello https://trello.com/c/FccRScmZ/28-s4-reservasi-disable-jam-waktu-ketika-sudah-lewat-dari-jam-pembuatan-reservasi ga ada info ini soalnya 😁 👍 

**Sip berarti issuenya ada 2:**
1. Naming method `CheckTimeEditValid` yang tidak clear, sehingga menimbulkan pertanyaan. Bagaimana kalau sekalian bikin checking, misal "isAllowEdit" yang returnnya boolean `true/false`. Sehingga nanti di validasi hanya tinggal pakai rule/checking ini 😁 
2. Concern penggunaan +7 ini, masih sama dengan issue https://github.com/jabardigitalservice/reservasi-backend/issues/46

**Comment by setiadijoe** [comment]
berarti bisa dilihat atuh itu PR nya maksudnya cara penulisannya apakah seperti itu atau perlu diubah

**Comment by yohang88** [comment]
Done aku udah comment di PR #54 ya. Sekalian malah aku update aja jadi 3 issue dari saya 😁 😆

**Comment by ayocodingit** [comment]
> I see, baru baca PR #26, berarti memang ada requirement baru ya itu (edit reservasi hanya bisa dilakukan 30 menit sebelum reservasi dimulai), saya cek di Trello https://trello.com/c/FccRScmZ/28-s4-reservasi-disable-jam-waktu-ketika-sudah-lewat-dari-jam-pembuatan-reservasi ga ada info ini soalnya grin +1
> 
> **Sip berarti issuenya ada 2:**
> 
>     1. Naming method `CheckTimeEditValid` yang tidak clear, sehingga menimbulkan pertanyaan. Bagaimana kalau sekalian bikin checking, misal `isAllowEdit()` yang returnnya boolean `true/false`. Sehingga nanti di validasi hanya tinggal pakai rule/checking ini grin
> 
>     2. Sebaiknya Eloquent Model tidak ada attribute yang berkaitan dengan checking validasi. Apalagi dibuat jadi Accessor. Accessor dan Mutator hanya dipakai untuk mentransform sebuah attribute dari/ke record database. https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor
> 
>     3. Concern penggunaan +7 ini, masih sama dengan issue #46

betul mas naming nya gak tepat :)
