### ISSUE TITLE
Middleware Authenticate tidak sesuai standar response

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/reservasi-backend#51]
https://github.com/jabardigitalservice/reservasi-backend/blob/0c2377f38231ef03a379d13e53492ae82c885c58/app/Http/Middleware/Authenticate.php#L17-L19

Logic ini justru tidak konsisten/abnormal 😁 

"Jika ekspektasi responsenya BUKAN JSON"
"Maka return balikannya adalah response JSON"

Bawaan default Laravel sudah aman, tidak perlu dirubah. Asalkan Request-nya dilakukan seperti berikut:
```
Header "Accept: application/json"
```

Hehe 😉

**Comment by ayocodingit** [comment]
![image](https://user-images.githubusercontent.com/41193120/108809785-32c5a280-75dc-11eb-96ec-184d392ea4c4.png)
itu asalnya gini mas @yohang88 
jadi pas redirect route('/login') tidak ditemukan

**Comment by yohang88** [comment]
@ayocodingit coba diskusi dengan @rizkyrmsyah dan @rachadiannovansyah yak, ini bagian dari materi bootcamp kemarin sih 😁

**Comment by ayocodingit** [comment]
Siapp

**Comment by setiadijoe** [comment]
reference with issue #42
